### ISSUE TITLE
FSB5 Multi-stream some files do not play properly, sounding garbled

### ISSUE THREAD

**Issue by Xehanort88** [kode54/vgmstream#119]
I am browing to my great delight the FSB5 FFX archive: however, certain songs (usually towards the end of the stream) are absolutely unplayable and garbled, in both the remaster and PS2 stream.

Specifically, "Summoned beast battle" in the ps2 stream (amongst many others) and a couple of the very last ones of the Remastered stream (fewer than the ps2 stream) are garbled. Very. Converting doesn't fix them.

Sound format is identified as XBOX 4-bit IMA ADPCM.

sample is greater than 1 gb so will upload later.

EDIT: DELETED
Folder with the FSB files.

**Comment by Xehanort88** [comment]
Update: Lord help me why, but splitting the FSB5 in single-stream FSBs makes even the garbled files work all right.

**Comment by bnnm** [comment]
Minor bug, the subsong position was off as I had never seen an FSB5 that big. Will fix later.
FSB5s bigger than ~1.1GB will probably have this problem too, but I need to see one to fix.
I understand this is from the PC version?

**Comment by Xehanort88** [comment]
Ah, so it was a bug - not me playing in Foobar2000 settings :)

Yes, both FSBs come from my PC version.
May I delete safely the folder from my MEGA now?

**Comment by bnnm** [comment]
You can delete, I got them.

**Comment by Xehanort88** [comment]
Thanks a lot!

**Comment by Xehanort88** [comment]
Update: somehow, extracting the file does not allow VGMstream to play it properly. I suspect it's an issue with the extractor because the FSB can be played just fine, but the extracted file can't.

https://mega.nz/#!cpNi2KiS!hEReEVO3OfL6QW0VbL_EJX7sNfWprQAAo8TDsdwmdP8

Error message by FSB extractor: 

> some of the extracted files use IMA ADPCM and this tool has assigned them the codec 0x69 (Xbox ADPCM) but if you want to play them immediately with VLC or mplayer you must add the -A option to fsbext so that they will be created with the codec 0x01 (IMA ADPCM)

**Comment by bnnm** [comment]
Their bug. FFX's subsongs work great now in my test version.

FSB Extractor / fsbext is not a good tool if you want FSB's subsongs into single files, you should "split" using [fsbii](http://hcs64.com/files/fsbii08.zip) (for FSB1~4), or [fsb5_split](http://kirby.cyberbotx.com/fsb5_split.exe) (for FSB5). Both tools roughly work like vgmstream's subsongs. Then you could use fsbext, but read on.

FSBs are not archives like a zip file with WAVs or such inside; they are a proper music format with custom header + custom data. fsbext doesn't "extract" anything but "transforms" the FSB to another format, modifying the data if needed.

For example FSB MP3s are not standard MP3s, so they are changed so MP3 players can play them. But it can't do OGG since FSB OGGs are very customized and transforming to a normal .ogg is much harder (even though it's possible to do like FSB MP3s).

**Comment by Xehanort88** [comment]
That makes my life relatively easier. So I may just convert directly from individual streams from foobar?

**Comment by bnnm** [comment]
I've fixed this.

foobar conversions would be lossy. While fsbext converts losslessy enough.

All I'm I saying is that fsbext is modifying the original data, even if it tries to be lossless (= not a plain extraction). So you can use it to make files for other players, but for archiving I'd keep the original FSBs.

**Comment by Xehanort88** [comment]
I agree.
