### ISSUE TITLE
Suggestions for test.exe

### ISSUE THREAD

**Issue by MichaelPriebe** [kode54/vgmstream#144]
Create minimum length parameter so the program will automatically use the loops to get it above that duration.
Automatic output should use the original file name and not the word 'dump'

**Comment by bnnm** [comment]
Original filename would be ok I guess. Note that test.exe converts .wav too so it'd need to be (filename.ext).wav to avoid overwritting the original.

Minimum duration I'm not sure when would be useful. Max duration I could understand, if one wants max ~3 mins. Still seems a bit too esoteric tho.

**Comment by MichaelPriebe** [comment]
For example let's say you want to make a song loop for one hour. You would
have to keep converting it and changing how many loops until you figure out
what's enough to make it an hour. And doing this in batch would be a
nightmare.

**Comment by bnnm** [comment]
I'll give it a thought but the idea still seems weird to me, and implementation strange for such an specific use-case.

Note that test.exe can generate .wav with loop points, maybe other tool already does what you ask using the info.

You could also put something like 60-80 loops that would guarantee +1h, then use something like [SoX](http://sox.sourceforge.net) to trim your file (IIRC: `sox.exe infile.wav outfile.wav fade t 0 60:00 10 pad 0 1`)

**Comment by iskunk** [comment]
I'd like to make a couple of suggestions:

1) Rename the program to something more specific, like "vgmdecode" or "vgmdec". It may be intended as a test program, but it's useful as a standalone utility in its own right. This will make things easier for Linux distributions packaging this project, as they won't have to rename the program (Unix systems already have a standard "test" utility).

2) Extend the "test" program slightly to support live output, making it usable as a command-line player. The idea is to create an analogue to minimal player utilities like mpg123/mpg321, ogg123, modplug123 et al. (thus suggesting a name of "vgm123" or the like). All of these use the [libao](https://www.xiph.org/ao/) library for sound output.

For my part, I'm on Linux, and fb2k isn't as readily available as I'd like. I'd be happy to contribute #2 if the idea sounds good.

**Comment by bnnm** [comment]
1. I agree the name is inadequate but I hesitate to change it in Windows given it's most used there. For Linux though I don't think nobody would mind if changed in the makefiles and stuff. I'd keep the full vgmstream name though, for consistency with the other components and as plain vgm is a bit generic (there is a .vgm format even). Maybe vgmstream-cli, vgmstreamd, vgmstreamdec, etc.

2. As I don't know much about linux or those players/lib I can't quite comment, but perhaps a new module would be cleaner as it seems to add some dependencies, and would need several specific options I think.
I want to make a cleaner public API too so maybe it could be used with an existing player instead.
Note that there is already a "-p" flag to output to stdout for piping, maybe that would suffice.

**Comment by iskunk** [comment]
1. I guess the name is less important on Windows, since fewer users will be inclined to use a command-line tool there. But I'd suggest considering a Windows-side change in the future, maybe at a new major release when other big changes are being made. "vgmstream-cli" and "vgmstreamdec" are good names. (Adding a "d" to the end implies that the program is a daemon/server, which isn't the case.)

2. A new module to isolate dependencies would be reasonable IMO, even if some of the code is shared. The problem with targeting an existing player is that there's so many of them! Whichever one(s) you choose to support, most users are going to be left out. Writing sound to stdout is a very "Unix" approach, but on modern systems you can't really redirect to /dev/dsp anymore. Having a program that can play on its own is partly about making vgmstream itself immediately usable without external application dependencies, and partly about matching the approach that other sound-format libraries have taken, at least on the Unix side. The *123 programs are pretty bare-bones compared to WinAmp/fb2k/etc., but they still serve a useful purpose.

If you have no objections at least, I'll prepare a PR, and that can be judged on its own merits. I have a couple of Pokemon Mystery Dungeon soundtrack rips, and I really want a way to play them :-)

**Comment by bnnm** [comment]
I think I'll ask the guys at hcs64.com (main vgmstream forum) about the name change.

A new module (vgmstream123? vgmstream-play?) is probably for the best even with some repetition, we could always fuse later. In time I think I'll consolidate some of the plugin code but I'm not too bothered as long as it gives some clarity and minimizes dependencies.

Btw I'm just a contributor here, just adding my thoughts :), kode54 calls the shots but I don't think he'll have objections as long as it doesn't break anything. I'm the most active so I guess I kind of set the current direction.

**Comment by iskunk** [comment]
Will greatly appreciate the forum input. I'm a complete outsider here.

Yee-ouch, I see the test program isn't even built on Linux. Will have a bit more to do there, it seems.

By the way, on a tangent... I see the build system is currently hand-curated Visual Studio project files, quasi-generated Automake templates, and some custom stuff for MinGW. Has there been any discussion about possibly using [CMake](https://cmake.org/)? Because I suspect that might work better for a project like this...

**Comment by bnnm** [comment]
I believe some users were able to build the test dec for Linux and Mac with the non .mingw makefiles (there was a PR the other day), despite the mingw_* target names (it was used to cross-compile from Linux IIRC) but I rarely test those, plus FFmpeg isn't integrated yet. I'd like to improve and unify makefiles some day but I don't have much experience.
 
For a new build system, well. kode54 uses VS and I don't think he wants to change that (I think other casual devs use it too). I use gcc/mingw since it's what I knew (I can build with VS now but I'd rather not). Automake is used by the Audacius plugin for the dependencies I guess (I massaged the scripts a bit since 'auto'make devs bizarrely expects us to maintain lists of .c files, they can come and do it themselves if they want). CMake I don't know much about it but maybe it's simpler to improve the current makefiles, given how niche this project is.

**Comment by iskunk** [comment]
I've got the test program building (and working) now with a new Makefile.audacious.am, in any event. I'll submit a separate PR for that, plus a bit of cleanup to the Autotools side.

What's really nice about CMake is that you use a common set of build definitions (what targets get built, what source files, etc.) and from that, the CMake utility can generate Visual Studio projects, Xcode projects, Borland projects, Unix makefiles, MinGW makefiles, NMAKE makefiles, pretty much anything under the sun. Just on the Visual Studio side, it can produce projects for any version going back to MSVC6.

So the point is not abandoning VS for day-to-day dev work, but switching to a system where the VS projects (and all other build projects/makefiles) are derived from a common set of build definitions stored in CMakeLists.txt files. You have to download/install the CMake utility, and there is a configuration step where you run it (equivalent to running ./configure in Autotools), but then there's a *.sln file and you're off to the races.

(And this isn't some little pet build system that a handful of folks are using; a large number of projects have actually dropped Autotools support in favor of this.)

I get the impression that this project has been born and raised pretty well outside the mainstream of open-source software development, so it's possible that literally no one here has heard of CMake. At one time, where I work, I was maintaining Visual Studio project files in version control, and it made me tear my hair out. Even in 2005, CMake was such a godsend of a solution for that...

**Comment by bnnm** [comment]
Well, if you think it could help you or others go for it, as long as doesn't break the current VS/makefiles or needs maintained .c lists, I hate those.

Just saying the very few devs here are used to something or other and won't find immediate need to change (maybe given time). Automake could get replaced as I doubt Linux users would miss it (they have it easy with package managers and stuff) but in Windows it adds some extra hoops.

If you write some simple instructions I'll throw in notes in my humble [build doc](https://github.com/kode54/vgmstream/blob/master/BUILD.md).

**Comment by iskunk** [comment]
I bring up CMake more as a point of discussion than anything; it's a bit of a big undertaking for a solo contribution. (You have to maintain lists of .c files in the VS projects anyway... there's no getting away from that ^_^)

From where I stand it's a pretty desirable solution, but you have to be familiar with the tool, what it does, and (importantly) its prevalence in general OSS development. So I want to make sure folks here at least know about it.

All that aside, I have a working vgmstream123 :-)  I'm now fixing up corner cases and adding polish. It's looking pretty good.

**Comment by iskunk** [comment]
```
$ ./test/vgmstream123 -h
vgmstream123 r1050-40-g33563f4, built Dec 23 2017

Usage: ./test/vgmstream123 [options] INFILE ...
Play streamed audio from video games.

Options:
    -b N         Use an audio buffer of N kilobytes [16]
    -d DRV       Use output driver DRV; available drivers:
                 pulse esd alsa oss nas null wav raw au 
    -f OUTFILE   Set output filename for a file driver specified with -d
    -o KEY:VAL   Pass option KEY with value VAL to the output driver
                 (see https://www.xiph.org/ao/doc/drivers.html)
    -@ LISTFILE  Read playlist from LISTFILE
    -h           Print this help
    -r           Repeat playback indefinitely
    -v           Display stream metadata and playback progress
    -D T         Set fade delay time T, in seconds [0.0]
    -F T         Set fade time T, in seconds [10.0]
    -L N         Loop N times [2]
    -S N         Play substream with index N [0]

INFILE can be any stream file type supported by vgmstream, or an .m3u/.m3u8
playlist referring to same. This program supports the "EXT-X-VGMSTREAM" tag
in playlists, and files compressed with gzip/bzip2/xz.
```

**Comment by bnnm** [comment]
Looks good, I'll page @kode54 in case he wants to comment.

**Comment by kode54** [comment]
Looks good, if someone wants to contribute the source and/or build scripts to produce it.

**Comment by iskunk** [comment]
Thanks @bnnm, @kode54. Please give the new player a try if you have the time. The program will likely need a bit of porting to work on Windows, but I tried to keep the POSIX stuff to a minimum.

This ended up not sharing any code with the test program, since the test program didn't really provide re-usable functions. Most of what's in there is glue code anyway; vgmstream and libao are where the real magic happens.

@MichaelPriebe, I added an option for minimum-play-time which you may find useful. I tried to implement output filenames based on the input, but the attempt got a bit messier than planned. If you can describe your use case, I might give that another try.

**Comment by bnnm** [comment]
I don't use Linux myself so I'll see if I can get it working in Windows later.

As for the name I think I'll start by renaming the test folder to "cli" and stuff.

For the minimum-play-time I though the calcs and glue would make the code a bit too messy too, hence I suggested other alternatives.

**Comment by iskunk** [comment]
I'll be happy to help with that from the Linux side; I'd like the program to be cross-platform. "cli" sounds like a good name for the folder.

I thought your objection to minimum-play-time was that it was too specialized a use case. The calculation itself is pretty straightforward, just a rearrangement of the formula in get_vgmstream_play_samples(). The only pitfall I saw was that a play time of 14+ hours (at 44.1 kHz) will result in more samples than can be represented in an int32_t.

On a separate note, a couple tidbits about vgmstream123 that should be documented somewhere:

1. The program supports playback of stream files that are compressed with gzip/bzip2/xz, as identified by a .gz/.bz2/.xz extension. The file will be decompressed to a temp dir using the respective utility program (which must be installed and accessible) and then loaded.

   This will probably only be useful on Linux, as these compression types are not common on Windows. (Playback of stream files inside .zip files is a much more complicated problem, alas.)

2. The program's support for playlists will recognize a special extended-M3U tag specific to vgmstream of the following form:
```
#EXT-X-VGMSTREAM:LOOPCOUNT=2,FADETIME=10.0,FADEDELAY=0.0,STREAMINDEX=0
```
(Any subset of these four parameters may appear in the line, in any order)

When this "magic comment" appears in the playlist before a vgmstream-compatible file, the given parameters will be applied to the playback of said file. This makes it feasible to play vgmstream files directly instead of needing to make "arranged" WAV/MP3 conversions ahead of time.

The tag syntax follows the conventions established in Apple's [HTTP Live Streaming standard](https://developer.apple.com/library/content/technotes/tn2288/_index.html), which was the only doc I could find that discussed extending M3U with arbitrary tags.

**Comment by bnnm** [comment]
@iskunk - vgmstream123 now builds on Windows (needs external libao.dll). Mingw can probably emulate POSIX stuff but I just patched it (for MSVC and co), could be improved later (will close on CTRL+C and no playlists/decompression). Didn't test much though.
I also renamed the test > cli folder, I'll test.c > vgmstream_cli.c next and later the .exe I guess, in fun steps.

**Comment by iskunk** [comment]
Hi @bnnm, glad you were able to get it working---not least the Libao build, which is [a bit dodgy](https://gitlab.xiph.org/xiph/libao/issues/2286) on Windows.

Decompression is no big deal, but the playlist code gave you trouble? That should be pretty straight C.

Renaming test.c will be good. Though on Linux at least, hyphens are more customary; I hardly ever see underscores in program names.

**Comment by bnnm** [comment]
TBH I had trouble too so I cheated and used a precompiled DLL from [here](https://github.com/goldendict/goldendict/tree/master/winlibs/lib). Playlist are borked due to using POSIX's getline, easiest to fix.

I don't mind hyphen or underscode but since the rest of the project only uses underscores in filenames I'd thought to follow that, the program name itself can still be vgmstream-cli.

**Comment by iskunk** [comment]
Oh, okay, I see. I did some work on Libao's build system since it wasn't quite where I wanted it to be the last time I worked with it. If you'd like to build the DLL yourself, it should be a lot easier after my patch.

Ah, yes, getline()... that's actually a GNU extension; I forgot about that. Should've used fgets() with a fixed buffer...

(I see what you mean about the underscores in file names)
