### ISSUE TITLE
Add support for multitrack .scd audio

### ISSUE THREAD

**Issue by VIRGINKLM** [kode54/vgmstream#15]
Used in games such as Final Fantasy XIII-2, Lightning Returns: Final Fantasy XIII and a couple files in Kingdom Hearts HD 1.5 Remix and Kingdom Hearts HD 2.5 Remix to name a few.
If you need any files as reference, let me know.

**Comment by bnnm** [comment]
Those multitracks (for XIII-2 OGGs at least) have channels for all tracks playing at the same time. Ex. ch1+2 are track1, ch3+4 are track2. The game then silences/crossfades channels.

A way to unmix them is to use the Channel Mixer DSP plugin in foobar2000.

As a test, since ignoring channels to get a 2ch track wasn't so easy, I added a volume control per channel (iirc some adx and brstm could use too).
Then, when loading the SCD and depending on how it's named channels are muted.

I'm not sure if this would be useful in the main codebase though.

**Comment by VIRGINKLM** [comment]
Sounds as a good option for playback. It would also be good to have somekind of option in case there are scd that simply playback all audio at the same time without fading to simply extract a 4 channel audio in some format (like wav). For example Kingdom Hearts 2 HD's Dearly Beloved, if you play it back on a 5.1 system the front speakers play back the avtual track and the rear speakers play the seashore sound effects which are both on a single .scd file encoded the same way.

**Comment by bnnm** [comment]
I added some stuff to get this working. See [here](https://hcs64.com/mboard/forum.php?showthread=8687&showpage=175#post_55625) but basically if you make an empty "filename.scd#c1,2.txtp" and open it it'll play filename.scd with only channels 1 and 2.

**Comment by kode54** [comment]
Why would you use that formatting in the filename? Commas aren't even legal filename characters in Windows.

**Comment by bnnm** [comment]
Comma is perfectly legal. Illegal characters:
*    < (less than)
*    \> (greater than)
*    : (colon)
*    " (double quote)
*    / (forward slash)
*    \ (backslash)
*    | (vertical bar or pipe)
*    ? (question mark)
*    \* (asterisk)

But other than a dot I could use anything as a separator, I thought a comma would be easy to understand.

**Comment by kode54** [comment]
Huh, I wonder why PowerShell wouldn't let me pipe to a name with a comma in it? Weird. I see Explorer lets me use it, though.
