### ISSUE TITLE
EAAC: Incorrect block type handling

### ISSUE THREAD

**Issue by NicknineTheEagle** [kode54/vgmstream#249]
https://github.com/kode54/vgmstream/blob/b5353846e3b7c602216ae936d02ce7554a94730d/src/meta/ea_eaac_streamfile.h#L49-L50
https://github.com/kode54/vgmstream/blob/b5353846e3b7c602216ae936d02ce7554a94730d/src/meta/ea_eaac_streamfile.h#L144-L145

This is incorrect, the last block *can* contain more audio data, so this behavior causes sounds to cut off early.

**Comment by NicknineTheEagle** [comment]
Wait, hold on, I've confused with earlier version with SNR/SNS, let me re-check this.

**Comment by NicknineTheEagle** [comment]
https://github.com/kode54/vgmstream/blob/b5353846e3b7c602216ae936d02ce7554a94730d/src/meta/ea_eaac.c#L269-L271

Is this really needed? Why not handle block headers in block_update_ea_sns?
I've tried to changing the code to do that and it works but the audio is *still* cut off at the end although to a lesser extent.

**Comment by bnnm** [comment]
I think I've fixed it so check the next update.

Evidently I don't do super complex things for fun. Basically I can't fix some EALayer3.2P files without massive rewrites otherwise ([more info](https://github.com/kode54/vgmstream/blob/master/src/coding/mpeg_custom_utils_ealayer3.c#L152)). Ideally vgmstream would be more flexible and could work with feed-based decoders but I do what I can.

EA block handling is AFAIK correct (v0/SNS=last block always has data, v1/SPS=last block never has data).

**Comment by AnonBaiter** [comment]
so what bnnm is saying is that the EAAC code can't be fixed without doing some complex math?

**Comment by NicknineTheEagle** [comment]
No, he was talking about a workaround for quirk of EAL32P codec. The bug I reported is unrelated to that.

**Comment by AnonBaiter** [comment]
well i must be missing something here

**Comment by NicknineTheEagle** [comment]
There's a bug in EAAC parser which causes EALayer3 sounds to cut off. I have speculated what might cause this and asked why something is done the way it's done and bnnm responded to that.

**Comment by NicknineTheEagle** [comment]
EACC EALayer3 bug fixed in https://github.com/kode54/vgmstream/commit/cbcacda6e47743e6d7608808a49d46dd21c8fab7
