### ISSUE TITLE
Unsupported IDSP/NUS3BANK (Taiko no Tatsujin, Switch)

### ISSUE THREAD

**Issue by bui** [kode54/vgmstream#255]
Taiko no Tatsujin (Nintendo Switch) uses NUS3BANK, but these specific files don't work with vgmstream's support for the format.

    > .\vgmstream.exe jingle_title.nus3bank
    failed opening jingle_title.nus3bank

Sample:
https://cdn.discordapp.com/attachments/108279526705860608/468109609102606356/jingle_title.nus3bank

Sample from a previous Taiko game on Wii U where NUS3BANK is supported by vgmstream:
https://cdn.discordapp.com/attachments/108279526705860608/468110170866581504/jingle_dress.nus3bank

**Comment by bxaimc** [comment]
You will need to extract the Opus files inside (OPUS magic) and name them “.lopus”. I added support for those in this commit: https://github.com/kode54/vgmstream/commit/5b3a00108204d4e39114a36bdec4eddcb22ccd1f 

NUS3BANKs are just containers that usually contain more than one file but in some cases (Taiko and Smash Bros) they do only have one file inside. NUS3s support in vgmstream was more of an misunderstanding of how to handle the container rather than extract the inner files and never should have been added to be honest :/

**Comment by bxaimc** [comment]
NUS3BANKs from Taiko/Smash on Wii U contain IDSPs inside, so those need to be extracted as well to be “correct”

**Comment by bnnm** [comment]
I've added a NUS3BANK parser for fun (having to find extractors is lame).  Now this works, and NUS3 IDSP code is pristine as it should.
I'll also mention (in case of frowning) those Namco IDSPs, OPUS and whatnot don't seem to exist outside NUS3BANK? May not even have an actual extension.

**Comment by bxaimc** [comment]
Afaik they don’t, except for AT3/9 and WAV of course. IDSPs and BNSF were also present in older NUS containers (.NUB) but headers were split from the raw data.
