### ISSUE TITLE
some .at3 files going 'numb' after midpoint, looping infinitely, causing crash or "bad allocation" message

### ISSUE THREAD

**Issue by Level99OCR** [kode54/vgmstream#27]
Sorry, hope you're not getting tired of me reporting bugs yet. 

Songs that go 'numb', they either take the last sound they processed at the midpoint/looppoint and play it forever, or if you skip directly there from silence it will continue to play silence forever. Ends up sometimes crashing the player or causing "bad allocation" messages for every song after it, requiring a restart:

Wipeout Pure - Data_0A
Zwei!! - 408 Final Battle Demon Vesper

Songs that somehow looped forever for me:

428 Fuusa Sareta Shubya de - bgm_c03.e01
Ace Combat Joint Assault - REGFILE_0000002C

**Comment by kode54** [comment]
I acquired a soundtrack rip of Wipeout Pure, but it contains no file named "Data_0A". All of the tracks have file names. And only two of the songs have .pos files, both Röyksopp songs, and both poorly named, as the included ZIP file does not use UTF-8 filenames. The .at3 files are correctly named, though, as the outer container is a .7z.

**Comment by Level99OCR** [comment]
The equivalent trackname from the "fixed" 7z (mine is old) is 14 T-Power - The System (7:21 in length) for Wipeout Pure. I tried both the new and the old rips, same kind of behavior though: after the midway point its either bugged or silent. Sometimes it crashes, sometimes it doesn't. The Zwei!! is in zzz_old on joshw. Zwei 408 Final Battle -Demon Vesper- is the one that bugs and never becomes silence, so silence detection can't compensate for the issue.

**Comment by Level99OCR** [comment]
Tales of Xillia 2 - BGM 72 (also AT3) causes foobar crash in mid-song.

**Comment by bananaman255** [comment]
I checked and I believe the problem is vgmstream isn't setting the total_samples properly. This isn't noticeable when there are loop points but causes problems if there aren't (like the Wipeout track above).

Rough fix, in riff.c:
- line 349: read fact_sample_count if it's an AT3 file
- line 395: sample_count = fact_sample_count

I can't compile the foobar plugin but it worked with test.exe

I could upload it but I'm not sure of side effects (I suspect all PSP/PS3 AT3 need this but no idea if there are other AT3).
