### ISSUE TITLE
[Request] Subsong name format option for foobar2000 component

### ISSUE THREAD

**Issue by NicknineTheEagle** [kode54/vgmstream#277]
Right now the name format for subsongs is hardcoded to be "filename#trackname" which means you don't get the ability to use the original track names for converted files.
It would be nice to be able to set the naming format in the component options as this would make mass conversion easier.

**Comment by bnnm** [comment]
I considered this before, but it was a very niche feature, required some boring code (potentially in several plugins), and devising a format convention (I agonise over such minor details), plus shouldn't be too hard to mass rename with the command line or some util.

So before that I want to unify and simplify plugin code first, so that adding plugin features would be easier.

**Comment by kode54** [comment]
It will probably be better to just fill out the meta "title" field with the trackname, or else not fill it out at all, and let the user decide how to format their display fields based on the presence or absence of tags. foobar2000 defaults to filling formatting requests for "%title%" with the filename minus extension if there is no meta "title" value.

**Comment by bnnm** [comment]
I don't think that would look good, because internal filenames often are worse than filenames (like a single letter or the same string for all files, which I can't really detect), so I preferred to show both.
What Nicknine suggested is ok I think, just not super high in my todo list, is all.

**Comment by bnnm** [comment]
I've added a foobar option in the latest PR so that TITLE tag isn't modified (=default filename minus extension), and these are now exported as meta tags:
- STREAM_NUMBER (current subsong, if file has subsongs, starts from 1)
- STREAM_COUNT (total subsongs, if file has subsongs)
- STREAM_NAME (internal name, that also exists in some formats without subsongs)

You should now be able to set any name using foobar's format functions, those 3, and some creativity.
Remember you may need to refresh tags: shift+right click > tagging > reload info.

The option isn't on by default since I don't think your average user changes/understands formatting, yet would want easy subsong names.

(also see new tags/playlist stuff)

**Comment by 203Null** [comment]
How can I turn on this option? I don't see STREAM_NAME in the metadata.

**Comment by bnnm** [comment]
First make sure your file has an internal name, and that vgmstream properly reads it (there are bugs and stuff...). Only a handful of formats do, like .fsb. Then right click > properties > should appear in the "metadata" tab. 

Then in preferences > playback > decoding > vgmstream check "override title". This just disabled appending the STREAM_NAME to %title%, then refresh tags if needed.

Then in preferences > display > default user interface (and on other places related to playlist IIRC), adjust the config, like "[%artist% - ]%title% [-- %STREAM_NAME%]]"
