### ISSUE TITLE
Update FFmpeg

### ISSUE THREAD

**Issue by bnnm** [kode54/vgmstream#315]
Paging @kode54 

I fixed an XMA bug in FFmpeg, and it'd be useful to update the lib so I can finally fix XMA looping here.

While we are at it, please also add to `--enable-decoder` these: `adpcm_ima_dk3,adpcm_ima_dk4`
(adds "duck" audio that was used in Sega Saturn vids.)

**Comment by kode54** [comment]
Wow, I'll deal with this in the morning.

I just updated my media autobuild suite, and made your changes to the configuration, and had to --disable-amf just to get it to link, because now there's a missing CoTaskMemFree symbol in the AMF crap. And the resulting binaries are over 12MB larger.

And wow, looks like I'm statically linking both iconv and SDL2. And a bunch of video acceleration libraries.

Also, do we really need the bink video codec? Can't it decode bink audio without that?

**Comment by bnnm** [comment]
Thanks. You are right, `bink` can be removed from `--enable-decoder` (but not from `--enable-demuxer`), I tested and it only needs `binkaudio_dct,binkaudio_rdft`. `ffmpeg_options.txt` may need to get updated too btw.

I suspect they are autodetected/disabled and unnecessary but in my tests builds I also set: `--disable-devices`, `--disable-iconv`, `--disable-schannel`, `--disable-nvenc`
