### ISSUE TITLE
Some AT3 files crash

### ISSUE THREAD

**Issue by kode54** [kode54/vgmstream#49]
[I was noticing that some PSP rips seemed to be working and some didn't, crashing the player upon adding to playlist. With Wild ARMs XF, every at3 is fine except "415b Noriyasu Agematsu -  FINAL DISASTER (1).at3"]

**Comment by bnnm** [comment]
Looks like it's looping is doing weird things, I'll look into it soon.

It doesn't crash in test.exe and Winamp for me though and I'm not sure why it would crash before playing.

**Comment by bnnm** [comment]
I've tested it a bit and any FFmpeg file (ex. mp4.vgmstream) will crash foobar. With my simplified DLLs crashes too.
Some WA XF use ATRAC3 (415b) and others ATRAC3plus (415a); since you have maiat3 enabled only 415b crashes it.

Maybe it's a linking issue? [The docs](https://ffmpeg.org/platform.html#Linking-to-FFmpeg-with-Microsoft-Visual-C_002b_002b) mention something about setting "References to No (/OPT:NOREF)" in MSVC for libs created by GCC/dlltool, and some extra steps.
You could try a full rebuild in Debug just in case (I take it autodisables the stuff mentioned in the docs?)

For the loop problem, I forgot I had normal (non ACCURATE) looping enabled, which is currently broken. Phew!

**Comment by kode54** [comment]
This is now fixed, as it was an issue with /opt:ref. I created my own import libraries from the .def files, which solves the issue without resulting in binary bloat.
